<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <LangVersion>14.0</LangVersion>
    <Nullable>Enable</Nullable>
    <TargetFramework>net10.0</TargetFramework>
    <BaseOutputPath>Avalonia\</BaseOutputPath>
  </PropertyGroup>
	
  <ItemGroup>
    <None Remove="Images\BuildImg.svg" />
    <None Remove="Images\FilesImg.svg" />
    <None Remove="Images\ModelImg.svg" />
    <None Remove="Images\PhotoImg.svg" />
    <None Remove="Images\VideoImg.svg" />
  </ItemGroup>
	
  <ItemGroup>
    <AvaloniaResource Include="Images\BuildImg.svg" />
    <AvaloniaResource Include="Images\FilesImg.svg" />
    <AvaloniaResource Include="Images\ModelImg.svg" />
    <AvaloniaResource Include="Images\PhotoImg.svg" />
    <AvaloniaResource Include="Images\VideoImg.svg" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.13" />
    <PackageReference Include="Xaml.Behaviors.Avalonia" Version="12.0.0.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
	<PackageReference Include="Material.Avalonia" Version="3.17.0" />
    <PackageReference Include="EPPlus" Version="8.6.1" />
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="YoloSharpOnnx" Version="3.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
	<PackageReference Include="Avalonia.Labs.CommandManager" Version="12.0.2" />
  </ItemGroup>

  <ItemGroup Condition="'$(OS)' == 'Windows_NT'">
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.24.4" />
	<PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260602" />
  </ItemGroup>
	
  <ItemGroup Condition="'$(OS)' != 'Windows_NT'">
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu.Linux" Version="1.26.0" />
	<PackageReference Include="OpenCvSharp4.official.runtime.linux-x64" Version="4.13.0.20260602" />
  </ItemGroup>
</Project>