global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Controls.ApplicationLifetimes;
global using Avalonia.Data;
global using Avalonia.Data.Converters;
global using Avalonia.Input;
global using Avalonia.Interactivity;
global using Avalonia.Markup.Xaml;
global using Avalonia.Platform.Storage;
global using Avalonia.Threading;
global using MsBox.Avalonia;
global using MsBox.Avalonia.Enums;
global using OpenCvSharp;
global using SewerDeformationSoftware.Logics.Cores;
global using SewerDeformationSoftware.Logics.Utils;
global using SewerDeformationSoftware.Logics.ViewModels;
global using SewerDeformationSoftware.Views;
global using System;
global using System.Buffers;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Runtime.CompilerServices;
global using System.Threading.Tasks;
global using System.Windows.Input;
global using YoloSharpOnnx;
global using YoloSharpOnnx.DataResult;
global using YoloSharpOnnx.Providers;
global using Point = OpenCvSharp.Point;
global using Size = OpenCvSharp.Size;
global using Window = Avalonia.Controls.Window;